@extends('layouts.app')
@section('context',$o->semester.' · '.$o->name)
@section('content')
<x-page-header :title="($row?'Edit':'Tambah').' tugas'" :crumbs="['Pengumpulan' => route('collections.index',$o->id), 'Kelola tugas' => route('assignments.index',$o->id), ($row?'Edit tugas':'Tambah tugas') => null]" /><form method="post" action="{{ $row?route('assignments.update',[$o->id,$row->id]):route('assignments.store',$o->id) }}" class="card" data-dirty-form data-confirm="Simpan tugas bersama seluruh sesi?">@csrf<div class="card-body">
@if($row)@method('PUT')<input type="hidden" name="version" value="{{ old('version',$row->version) }}">@endif
<label for="title" class="form-label">Judul</label><input id="title" name="title" class="form-control mb-3" required maxlength="180" value="{{ old('title',$row?->title) }}">
@foreach(['type'=>\App\Services\Assessment::TYPES,'mode'=>\App\Services\Assessment::MODES] as $field=>$options)<label for="{{ $field }}" class="form-label">{{ $field==='type'?'Jenis tugas':'Mode pengumpulan' }}</label><select id="{{ $field }}" name="{{ $field }}" class="form-select mb-3" required>@foreach($options as $key=>$label)<option value="{{ $key }}" @selected(old($field,$row?->$field)===$key)>{{ $label }}</option>@endforeach</select>@endforeach
<label for="origin_meeting_id" class="form-label">Pertemuan asal</label><select id="origin_meeting_id" name="origin_meeting_id" class="form-select mb-3"><option value="">Tanpa asal — laporan akhir/lainnya</option>@foreach($meetings as $m)<option value="{{ $m->id }}" @selected(old('origin_meeting_id',$row?->origin_meeting_id)==$m->id)>{{ $m->number }} · {{ $m->title }}</option>@endforeach</select>
<p class="small text-secondary">Aktivitas 1 tetap berasal dari pertemuan 1 walau diterima saat pertemuan 2. Jadwal pengumpulan diatur setelah menyimpan. Laporan akhir cetak tanpa asal; checklist Cover dan bagian 1–5 dibuat tanpa komponen nilai otomatis.</p>
<label for="instructions" class="form-label">Instruksi</label><textarea id="instructions" name="instructions" class="form-control mb-3">{{ old('instructions',$row?->instructions) }}</textarea>
@foreach(['mandatory'=>'Kewajiban','active'=>'Status tugas'] as $field=>$label)<label class="form-label" for="{{ $field }}">{{ $label }}</label><select class="form-select mb-3" id="{{ $field }}" name="{{ $field }}"><option value="1" @selected(old($field,$row?->$field??1)==1)>{{ $field==='mandatory'?'Wajib':'Aktif' }}</option><option value="0" @selected(old($field,$row?->$field??1)==0)>{{ $field==='mandatory'?'Opsional':'Nonaktif' }}</option></select>@endforeach
@if($row)<label for="reason" class="form-label">Catatan (opsional)</label><textarea id="reason" name="reason" maxlength="1000" class="form-control mb-3">{{ old('reason') }}</textarea><label class="d-block mb-3"><input type="checkbox" name="confirmed" value="1" required> Konfirmasi perubahan tugas yang berlaku untuk praktikan.</label>@endif<button type="submit" class="btn btn-primary">Simpan tugas</button></div></form>
@endsection
