@extends('layouts.app')
@section('context',$o->semester.' · '.$o->name)
@section('content')
<x-page-header title="Jadwal pengumpulan" :subtitle="$a->title.' · Pertemuan asal '.($a->origin_meeting_id?DB::table('meetings')->where('id',$a->origin_meeting_id)->value('number'):'—')" :crumbs="['Pengumpulan' => route('collections.index',$o->id), 'Kelola tugas' => route('assignments.index',$o->id), $a->title => null, 'Jadwal' => null]" />
@foreach($sessions as $session)
@php $row=$rows->firstWhere('session_id',$session->id); @endphp
<form method="post" action="{{ route('assignments.schedule.save',[$o->id,$a->id]) }}" class="card mb-3" data-dirty-form data-confirm="Simpan jadwal sesi ini?">@csrf<div class="card-body"><h2>{{ $session->label }}</h2><input type="hidden" name="session_id" value="{{ $session->id }}"><input type="hidden" name="version" value="{{ $row?->version??0 }}"><label class="form-label" for="collection-{{ $session->id }}">Pelaksanaan pengumpulan (opsional)</label><select id="collection-{{ $session->id }}" name="collection_session_meeting_id" class="form-select mb-3"><option value="">Di luar pertemuan terjadwal</option>@foreach($executions->where('session_id',$session->id) as $sm)<option value="{{ $sm->id }}" @selected($row?->collection_session_meeting_id==$sm->id)>Pertemuan {{ $sm->number }} · {{ $sm->label }}</option>@endforeach</select>
<div class="row">@foreach(['opens_at'=>'Dibuka','due_at'=>'Deadline','closes_at'=>'Ditutup'] as $field=>$label)<div class="col-md-4"><label for="{{ $field }}-{{ $session->id }}" class="form-label">{{ $label }} · WIB</label><input id="{{ $field }}-{{ $session->id }}" type="datetime-local" name="{{ $field }}" class="form-control mb-3" required value="{{ $row?\Carbon\CarbonImmutable::parse($row->$field,'UTC')->setTimezone('Asia/Jakarta')->format('Y-m-d\TH:i'):'' }}"></div>@endforeach</div>
<label class="form-label" for="late-{{ $session->id }}">Penerimaan setelah deadline sampai penutupan</label><select id="late-{{ $session->id }}" class="form-select mb-3" name="allow_late"><option value="0" @selected(!$row?->allow_late)>Tidak diizinkan</option><option value="1" @selected($row?->allow_late)>Diizinkan, tetap ditandai terlambat</option></select><label for="reason-{{ $session->id }}" class="form-label">Catatan (opsional)</label><input id="reason-{{ $session->id }}" name="reason" class="form-control mb-3" maxlength="1000"><label class="d-block mb-3"><input type="checkbox" name="confirmed" value="1" required> Konfirmasi jadwal pengumpulan untuk praktikan.</label><button type="submit" class="btn btn-primary">Simpan jadwal {{ $session->label }}</button></div></form>
@endforeach
<p class="small text-secondary">Jadwal yang sudah digunakan penerimaan tidak dapat diubah agar penentuan terlambat pada arsip tetap konsisten.</p>
@endsection
