<?php

use App\Http\Controllers\ActivityLogController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\AslabController;
use App\Http\Controllers\AssignmentController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AttendanceOverviewController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BackupController;
use App\Http\Controllers\CollectionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\MasterController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\PortalIdentityController;
use App\Http\Controllers\PublicDeliveryController;
use App\Http\Controllers\PublicPortalController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RequestController;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubmissionController;
use Illuminate\Support\Facades\Route;

Route::get('/health/ready', [HealthController::class, 'ready']);
Route::get('/', HomeController::class)->name('home');
// Old single-practicum URLs keep working: GET forwards to the practicum portal (or the picker); legacy POSTs
// are accepted only for the current public offering of the submitted practicum.
Route::get('/modul', [HomeController::class, 'legacy'])->name('legacy.materials');
Route::get('/modul/{material}/unduh', [MaterialController::class, 'legacyDownload'])->whereNumber('material')->name('legacy.materials.download');
Route::get('/{page}', [HomeController::class, 'legacy'])->whereIn('page', array_keys(PublicPortalController::PAGES))->name('legacy.page');
Route::post('/pengumpulan', [PublicPortalController::class, 'submit'])->middleware('throttle:public-submit')->name('legacy.submit');
Route::post('/pengajuan', [PublicPortalController::class, 'requestStore'])->middleware('throttle:public-submit')->name('legacy.requests.store');
// General announcements (no practicum); practicum announcements live under /{slug}/pengumuman.
Route::get('/pengumuman', [AnnouncementController::class, 'publicIndex'])->name('public.announcements.index');
Route::get('/pengumuman/{id}', [AnnouncementController::class, 'publicShow'])->whereNumber('id')->name('public.announcements.show');
Route::get('/sampul/{practicum}', [PortalIdentityController::class, 'cover'])->whereNumber('practicum')->name('portal.cover');
Route::get('/cek-status', [PublicPortalController::class, 'statusForm'])->name('public.status');
Route::post('/cek-status', [PublicPortalController::class, 'status'])->middleware('throttle:public-status')->name('public.status.check');
Route::post('/cek-status/rincian', [PublicPortalController::class, 'statusJson'])->middleware('throttle:public-status')->name('public.status.detail');
Route::post('/cek-status/semua', [PublicPortalController::class, 'statusBatch'])->middleware('throttle:public-status')->name('public.status.batch');
Route::post('/cek-status/revisi', [PublicPortalController::class, 'revise'])->middleware('throttle:public-submit')->name('public.revise');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'create'])->name('login');
    Route::post('/login', [AuthController::class, 'store'])->middleware('throttle:20,1');
});
Route::middleware(['auth', 'active', 'auth.session'])->group(function () {
    Route::post('/logout', [AuthController::class, 'destroy'])->name('logout');
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/praktikum/{offering}', [DashboardController::class, 'offering'])->whereNumber('offering')->name('offering');
    Route::get('/praktikum/{offering}/sesi/{session}', [DashboardController::class, 'session'])->whereNumber(['offering', 'session'])->name('session');
    Route::get('/pengaturan/backup', [BackupController::class, 'index'])->name('backup.index');
    Route::post('/pengaturan/backup', [BackupController::class, 'run'])->name('backup.run');
    Route::middleware('admin')->prefix('pengaturan')->group(function () {
        Route::get('/', [SettingsController::class, 'index'])->name('settings.index');
        Route::post('/backup/jadwal', [BackupController::class, 'settings'])->name('backup.settings');
        Route::get('/log-aktivitas', [ActivityLogController::class, 'index'])->name('logs.index');
        Route::get('/log-aktivitas/{id}', [ActivityLogController::class, 'show'])->whereNumber('id')->name('logs.show');
        Route::get('/aslab', [AslabController::class, 'index'])->name('aslab.index');
        Route::get('/aslab/baru', [AslabController::class, 'create'])->name('aslab.create');
        Route::post('/aslab', [AslabController::class, 'store'])->name('aslab.store');
        Route::get('/aslab/{aslab}', [AslabController::class, 'edit'])->name('aslab.edit');
        Route::put('/aslab/{aslab}', [AslabController::class, 'update'])->name('aslab.update');
    });

    Route::middleware('admin')->prefix('pengaturan/master/{type}')->whereIn('type', ['semester', 'praktikum', 'offering'])->group(function () {
        Route::get('/', [MasterController::class, 'index'])->name('master.index');
        Route::get('/baru', [MasterController::class, 'form'])->name('master.create');
        Route::post('/', [MasterController::class, 'save'])->name('master.store');
        Route::get('/{id}/edit', [MasterController::class, 'form'])->whereNumber('id')->name('master.edit');
        Route::put('/{id}', [MasterController::class, 'save'])->whereNumber('id')->name('master.update');
        Route::post('/{id}/kunci', [MasterController::class, 'lock'])->whereNumber('id')->name('master.lock');
        Route::delete('/{id}', [MasterController::class, 'destroy'])->whereNumber('id')->name('master.destroy');
    });
    Route::prefix('praktikum/{offering}')->whereNumber('offering')->group(function () {
        Route::get('/rekap', [ReportController::class, 'index'])->name('reports.index');
        Route::get('/log-aktivitas', [ActivityLogController::class, 'index'])->name('logs.offering');
        Route::get('/log-aktivitas/{id}', [ActivityLogController::class, 'showOffering'])->whereNumber('id')->name('logs.offering.show');
        Route::get('/tampilan-portal', [PortalIdentityController::class, 'edit'])->name('portal-identity.edit');
        Route::post('/tampilan-portal', [PortalIdentityController::class, 'update'])->name('portal-identity.update');
        Route::get('/kelola-pengumuman', [AnnouncementController::class, 'index'])->name('announcements.index');
        Route::get('/kelola-pengumuman/baru', [AnnouncementController::class, 'form'])->name('announcements.create');
        Route::post('/kelola-pengumuman', [AnnouncementController::class, 'save'])->name('announcements.store');
        Route::get('/kelola-pengumuman/{id}', [AnnouncementController::class, 'form'])->whereNumber('id')->name('announcements.edit');
        Route::post('/kelola-pengumuman/{id}', [AnnouncementController::class, 'save'])->whereNumber('id')->name('announcements.update');
        Route::post('/kelola-pengumuman/{id}/arsip', [AnnouncementController::class, 'archive'])->whereNumber('id')->name('announcements.archive');
        Route::get('/pengajuan', [RequestController::class, 'index'])->name('requests.index');
        Route::get('/pengajuan/pengaturan', [RequestController::class, 'settings'])->name('requests.settings');
        Route::post('/pengajuan/periode', [RequestController::class, 'windowSave'])->name('requests.window');
        Route::post('/pengajuan/remidi', [RequestController::class, 'programSave'])->name('requests.program');
        Route::get('/pengajuan/{id}', [RequestController::class, 'show'])->whereNumber('id')->name('requests.show');
        Route::post('/pengajuan/{id}/keputusan', [RequestController::class, 'decide'])->whereNumber('id')->name('requests.decide');
        Route::post('/pengajuan/{id}/hasil', [RequestController::class, 'result'])->whereNumber('id')->name('requests.result');
        Route::post('/pengajuan/{id}/token-baru', [RequestController::class, 'reissue'])->whereNumber('id')->name('requests.reissue');
        Route::get('/pengajuan/{id}/bukti', [RequestController::class, 'download'])->whereNumber('id')->name('requests.download');
        Route::get('/kiriman-digital', [PublicDeliveryController::class, 'index'])->name('deliveries.index');
        Route::get('/kiriman-digital/{id}/unduh', [PublicDeliveryController::class, 'download'])->whereNumber('id')->name('deliveries.download');
        Route::post('/kiriman-digital/{id}', [PublicDeliveryController::class, 'decide'])->whereNumber('id')->name('deliveries.decide');
        Route::get('/kiriman-digital/{id}/token-baru', [PublicDeliveryController::class, 'reissueForm'])->whereNumber('id')->name('deliveries.reissue.form');
        Route::post('/kiriman-digital/{id}/token-baru', [PublicDeliveryController::class, 'reissue'])->whereNumber('id')->name('deliveries.reissue');
        Route::get('/pengumpulan', [CollectionController::class, 'index'])->name('collections.index');
        Route::get('/laporan-akhir', [CollectionController::class, 'finalReports'])->name('final-reports.index');
        Route::get('/tugas', [AssignmentController::class, 'index'])->name('assignments.index');
        Route::get('/tugas/baru', [AssignmentController::class, 'form'])->name('assignments.create');
        Route::post('/tugas', [AssignmentController::class, 'save'])->name('assignments.store');
        Route::get('/tugas/{id}/edit', [AssignmentController::class, 'form'])->whereNumber('id')->name('assignments.edit');
        Route::put('/tugas/{id}', [AssignmentController::class, 'save'])->whereNumber('id')->name('assignments.update');
        Route::get('/tugas/{assignment}/jadwal', [AssignmentController::class, 'schedules'])->whereNumber('assignment')->name('assignments.schedules');
        Route::post('/tugas/{assignment}/jadwal', [AssignmentController::class, 'scheduleSave'])->whereNumber('assignment')->name('assignments.schedule.save');
        Route::get('/tugas/{assignment}/penerimaan', [SubmissionController::class, 'index'])->whereNumber('assignment')->name('submissions.index');
        Route::get('/tugas/{assignment}/penerimaan/{enrollment}', [SubmissionController::class, 'form'])->whereNumber(['assignment', 'enrollment'])->name('submissions.form');
        Route::post('/tugas/{assignment}/penerimaan/{enrollment}', [SubmissionController::class, 'save'])->whereNumber(['assignment', 'enrollment'])->middleware('throttle:40,1')->name('submissions.save');
        Route::post('/tugas/{assignment}/penerimaan/{enrollment}/checklist', [SubmissionController::class, 'checklist'])->whereNumber(['assignment', 'enrollment'])->name('submissions.checklist');
        Route::get('/tugas/{assignment}/penerimaan/{enrollment}/versi/{version}', [SubmissionController::class, 'download'])->whereNumber(['assignment', 'enrollment', 'version'])->name('submissions.download');
        Route::get('/nilai', [GradeController::class, 'index'])->name('grades.index');
        Route::get('/nilai/{enrollment}', [GradeController::class, 'form'])->whereNumber('enrollment')->name('grades.form');
        Route::post('/nilai/{enrollment}', [GradeController::class, 'save'])->whereNumber('enrollment')->name('grades.save');
        Route::get('/nilai/{enrollment}/final', [GradeController::class, 'finalForm'])->whereNumber('enrollment')->name('grades.final');
        Route::post('/nilai/{enrollment}/final', [GradeController::class, 'finalize'])->whereNumber('enrollment')->name('grades.finalize');
        Route::post('/nilai/{enrollment}/final/buka', [GradeController::class, 'reopen'])->whereNumber('enrollment')->name('grades.reopen');
        Route::get('/komponen-nilai', [GradeController::class, 'components'])->name('grades.components');
        Route::post('/komponen-nilai', [GradeController::class, 'componentSave'])->name('grades.component.save');
        Route::get('/aturan-nilai', [GradeController::class, 'rules'])->name('grades.rules');
        Route::post('/aturan-nilai', [GradeController::class, 'ruleStore'])->name('grades.rules.store');
        Route::post('/aturan-nilai/{rule}/terbit', [GradeController::class, 'rulePublish'])->whereNumber('rule')->name('grades.rules.publish');
        Route::get('/pertemuan', [MeetingController::class, 'index'])->name('meetings.index');
        Route::get('/pertemuan/baru', [MeetingController::class, 'form'])->name('meetings.create');
        Route::post('/pertemuan', [MeetingController::class, 'save'])->name('meetings.store');
        Route::post('/pertemuan/awal', [MeetingController::class, 'defaults'])->name('meetings.defaults');
        Route::get('/pertemuan/{id}/edit', [MeetingController::class, 'form'])->whereNumber('id')->name('meetings.edit');
        Route::put('/pertemuan/{id}', [MeetingController::class, 'save'])->whereNumber('id')->name('meetings.update');
        Route::get('/pelaksanaan/baru', [MeetingController::class, 'executionForm'])->name('executions.create');
        Route::post('/pelaksanaan', [MeetingController::class, 'executionSave'])->name('executions.store');
        Route::get('/pelaksanaan/{id}/edit', [MeetingController::class, 'executionForm'])->whereNumber('id')->name('executions.edit');
        Route::put('/pelaksanaan/{id}', [MeetingController::class, 'executionSave'])->whereNumber('id')->name('executions.update');
        Route::get('/pertemuan/{meeting}/modul', [MaterialController::class, 'index'])->whereNumber('meeting')->name('materials.index');
        Route::post('/pertemuan/{meeting}/modul', [MaterialController::class, 'upload'])->whereNumber('meeting')->middleware('throttle:20,1')->name('materials.upload');
        Route::post('/pertemuan/{meeting}/modul/{material}/publikasi', [MaterialController::class, 'publish'])->whereNumber(['meeting', 'material'])->name('materials.publish');
        Route::get('/pertemuan/{meeting}/modul/{material}/unduh', [MaterialController::class, 'download'])->whereNumber(['meeting', 'material'])->name('materials.download');
        Route::get('/presensi', AttendanceOverviewController::class)->name('attendance.overview');
        Route::get('/presensi/{execution}', [AttendanceController::class, 'index'])->whereNumber('execution')->name('attendance.index');
        Route::get('/presensi/{execution}/peserta/{participant}/edit', [AttendanceController::class, 'edit'])->whereNumber(['execution', 'participant'])->name('attendance.edit');
        Route::post('/presensi/{execution}/snapshot', [AttendanceController::class, 'snapshot'])->whereNumber('execution')->name('attendance.snapshot');
        Route::post('/presensi/{execution}', [AttendanceController::class, 'save'])->whereNumber('execution')->name('attendance.save');
        Route::get('/presensi/{execution}/cetak', [AttendanceController::class, 'print'])->whereNumber('execution')->name('attendance.print');
        Route::post('/presensi/{execution}/scan', [AttendanceController::class, 'upload'])->whereNumber('execution')->middleware('throttle:20,1')->name('attendance.upload');
        Route::get('/presensi/{execution}/scan/{document}', [AttendanceController::class, 'download'])->whereNumber(['execution', 'document'])->name('attendance.download');
        Route::get('/sesi', [SessionController::class, 'index'])->name('sessions.index');
        Route::get('/sesi/baru', [SessionController::class, 'form'])->name('sessions.create');
        Route::post('/sesi', [SessionController::class, 'save'])->name('sessions.store');
        Route::get('/sesi/{id}/edit', [SessionController::class, 'form'])->whereNumber('id')->name('sessions.edit');
        Route::put('/sesi/{id}', [SessionController::class, 'save'])->whereNumber('id')->name('sessions.update');
        Route::delete('/sesi/{id}', [SessionController::class, 'destroy'])->whereNumber('id')->name('sessions.destroy');
        Route::get('/praktikan', [StudentController::class, 'index'])->name('students.index');
        Route::get('/praktikan/baru', [StudentController::class, 'form'])->name('students.create');
        Route::post('/praktikan', [StudentController::class, 'save'])->name('students.store');
        Route::get('/praktikan/{id}/edit', [StudentController::class, 'form'])->whereNumber('id')->name('students.edit');
        Route::put('/praktikan/{id}', [StudentController::class, 'save'])->whereNumber('id')->name('students.update');
        Route::post('/dosen', [StudentController::class, 'supervisor'])->name('supervisors.store');
        Route::post('/dosen/preview', [StudentController::class, 'bulkPreview'])->name('supervisors.preview');
        Route::post('/dosen/commit', [StudentController::class, 'bulkCommit'])->name('supervisors.commit');
        Route::get('/ekspor', [StudentController::class, 'export'])->name('students.export');
        Route::get('/impor/template', [ImportController::class, 'template'])->name('imports.template');
        Route::get('/impor', [ImportController::class, 'form'])->name('imports.form');
        Route::post('/impor', [ImportController::class, 'upload'])->name('imports.upload');
        Route::get('/impor/{token}', [ImportController::class, 'preview'])->whereUuid('token')->name('imports.preview');
        Route::post('/impor/{token}/map', [ImportController::class, 'map'])->whereUuid('token')->name('imports.map');
        Route::post('/impor/{token}/commit', [ImportController::class, 'commit'])->whereUuid('token')->name('imports.commit');
    });
});

// Practicum portals. Registered last so fixed paths always win; slugs never use reserved words (PracticumPortal::RESERVED).
Route::prefix('{slug}')->where(['slug' => '[a-z0-9]+(?:-[a-z0-9]+)*'])->middleware('portal')->group(function () {
    Route::get('/', [HomeController::class, 'portal'])->name('portal.home');
    Route::get('/pengumuman', [AnnouncementController::class, 'publicIndex'])->name('portal.announcements');
    Route::get('/pengumuman/{id}', [AnnouncementController::class, 'publicShow'])->whereNumber('id')->name('portal.announcement');
    Route::get('/modul', [MaterialController::class, 'publicIndex'])->defaults('service', 'modul')->name('portal.materials');
    Route::get('/modul/{material}/unduh', [MaterialController::class, 'publicDownload'])->whereNumber('material')->defaults('service', 'modul')->middleware('throttle:public-download')->name('portal.material.download');
    foreach (array_keys(PublicPortalController::PAGES) as $page) {
        Route::get('/'.$page, [PublicPortalController::class, 'page'])->defaults('page', $page)->defaults('service', $page)->name('portal.'.$page);
    }
    Route::post('/pengumpulan', [PublicPortalController::class, 'submit'])->defaults('service', 'pengumpulan')->middleware('throttle:public-submit')->name('portal.submit');
    Route::post('/pengajuan', [PublicPortalController::class, 'requestStore'])->defaults('service', 'pengajuan')->middleware('throttle:public-submit')->name('portal.request');
    Route::post('/remidi', [PublicPortalController::class, 'requestStore'])->defaults('service', 'remidi')->middleware('throttle:public-submit')->name('portal.remedial');
});
