@extends('layouts.app')
@section('context',$o->semester.' · '.$o->name)
@section('content')
<x-page-header title="Modul & Soal" :subtitle="'Pertemuan '.$meeting->number.' · '.$meeting->title.' · '.$o->name" :crumbs="['Pertemuan' => route('meetings.index',$o->id), 'Pertemuan '.$meeting->number => null, 'Modul' => null]" />
<div class="card mb-3"><div class="card-body table-responsive"><table class="table table-stack"><thead><tr><th>Judul</th><th>Berkas</th><th>Status</th><th>Publikasi</th></tr></thead><tbody>
@forelse($materials as $m)<tr><td>{{ $m->title }}</td><td><a href="{{ route('materials.download',[$o->id,$meeting->id,$m->id]) }}">{{ $m->original_name }}</a> · {{ number_format($m->size/1024,1) }} KB</td><td><span class="badge text-bg-light">{{ $m->published_at?'Diterbitkan':'Draf · privat' }}</span></td><td>@if($canShared)<form method="post" action="{{ route('materials.publish',[$o->id,$meeting->id,$m->id]) }}" data-confirm="Ubah ketersediaan publik materi ini?" class="material-publish" data-dirty-form>@csrf<input type="hidden" name="version" value="{{ $m->version }}"><input type="hidden" name="published" value="{{ $m->published_at?0:1 }}"><label class="visually-hidden" for="reason-{{ $m->id }}">Catatan publikasi {{ $m->title }}</label><input class="form-control mb-2" id="reason-{{ $m->id }}" name="reason" maxlength="1000" placeholder="Catatan (opsional)"><label class="d-block small mb-2"><input type="checkbox" name="confirmed" value="1" required> Konfirmasi {{ $m->published_at?'tarik dari publik':'unduhan publik' }}</label><button class="btn btn-sm btn-outline-primary" type="submit">{{ $m->published_at?'Tarik publikasi':'Terbitkan' }}</button></form>@else<span class="text-secondary">Perubahan publikasi membutuhkan akses seluruh sesi.</span>@endif</td></tr>
@empty<tr><td colspan="4" class="empty">Materi resmi belum tersedia. Tidak ada syllabus contoh yang diterbitkan.</td></tr>@endforelse</tbody></table>{{ $materials->links() }}</div></div>
@if($canShared)<form method="post" action="{{ route('materials.upload',[$o->id,$meeting->id]) }}" enctype="multipart/form-data" data-dirty-form data-confirm="Simpan modul baru sebagai draf privat?" class="card"><div class="card-body">@csrf<h2>Unggah modul / soal sebagai draf</h2><label class="form-label" for="title">Judul materi</label><input class="form-control mb-3" id="title" name="title" required maxlength="180" value="{{ old('title') }}"><label class="form-label" for="file">Berkas materi</label><input class="form-control mb-3" id="file" name="file" type="file" accept=".pdf,.docx,.zip,.txt,.sql" required><p class="small text-secondary">PDF/DOCX/ZIP/TXT/SQL, maksimum {{ config('academic.upload_max_kb')/1024 }} MB. Berkas tidak dieksekusi. Untuk revisi, unggah draf baru; berkas lama tetap tersimpan. Unduhan publik aktif hanya setelah Terbitkan.</p><button type="submit" class="btn btn-primary">Simpan draf modul</button></div></form>@endif
@endsection
