@extends('layouts.app')
@section('context',$o->semester.' · '.$o->name)
@section('content')
<x-page-header title="Nilai praktikan" :subtitle="$e->nbi.' · '.$e->name" :crumbs="['Penilaian' => route('grades.index',$o->id), $e->name => null]">
    <x-slot:actions><a class="btn btn-outline-primary" href="{{ route('grades.final',[$o->id,$e->id]) }}"><i class="bi bi-patch-check" aria-hidden="true"></i> Finalisasi</a></x-slot:actions>
</x-page-header>@if($finalized)<div class="alert alert-info">Hasil telah difinalisasi. Nilai read-only.</div>@endif
<form method="post" action="{{ route('grades.save',[$o->id,$e->id]) }}" class="card" data-dirty-form>@csrf<div class="card-body"><fieldset @disabled($finalized)>
@forelse($components as $c)@php $g=$grades->get($c->id); @endphp<div class="border rounded p-3 mb-3"><label class="form-label"><input type="checkbox" name="selected[]" value="{{ $c->id }}" @checked(in_array($c->id,old('selected',[])))> {{ $c->label }}</label><input type="hidden" name="rows[{{ $c->id }}][version]" value="{{ old('rows.'.$c->id.'.version',$g?->version??0) }}"><div class="row g-2"><div class="col-md-5"><label for="state-{{ $c->id }}" class="form-label">Status</label><select id="state-{{ $c->id }}" name="rows[{{ $c->id }}][status]" class="form-select">@foreach(['ungraded'=>'Belum diperiksa','graded'=>'Sudah dinilai','missing_zero'=>'Tidak dipenuhi — nilai nol diputuskan'] as $key=>$label)<option value="{{ $key }}" @selected(old('rows.'.$c->id.'.status',$g?->status??'ungraded')===$key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label" for="score-{{ $c->id }}">Nilai / {{ $c->max_score }}</label><input id="score-{{ $c->id }}" name="rows[{{ $c->id }}][score]" type="number" min="0" max="{{ $c->max_score }}" step="0.0001" class="form-control" value="{{ old('rows.'.$c->id.'.score',$g?->score) }}"></div><div class="col-md-4"><label class="form-label" for="note-{{ $c->id }}">Catatan</label><input id="note-{{ $c->id }}" name="rows[{{ $c->id }}][note]" class="form-control" value="{{ old('rows.'.$c->id.'.note',$g?->note) }}"></div></div></div>@empty<p>Belum ada komponen aktif. Pengelola berizin aturan nilai dapat menyiapkannya.</p>@endforelse
<label for="reason" class="form-label">Alasan — wajib bila mengoreksi nilai tersimpan atau memutuskan nol</label><textarea id="reason" name="reason" class="form-control mb-3" maxlength="1000">{{ old('reason') }}</textarea><button type="submit" class="btn btn-primary" @disabled($components->isEmpty())>Simpan nilai terpilih</button></fieldset></div></form>
@endsection
