@extends('layouts.app')
@section('context',$o->semester.' · '.$o->name)
@section('content')
<x-page-header title="Aturan nilai berversi" subtitle="Draf tidak mengizinkan finalisasi. Terbitkan hanya setelah sesuai ketentuan resmi. Perubahan komponen membutuhkan versi draf baru." :crumbs="['Penilaian' => route('grades.index',$o->id), 'Aturan nilai' => null]">
    <x-slot:actions><a class="btn btn-outline-primary" href="{{ route('grades.components',$o->id) }}"><i class="bi bi-ui-checks-grid" aria-hidden="true"></i> Komponen nilai</a></x-slot:actions>
</x-page-header>
<form method="post" action="{{ route('grades.rules.store',$o->id) }}" class="card mb-3" data-dirty-form data-confirm="Simpan aturan sebagai draf baru?">@csrf<div class="card-body"><h2>Versi draf baru</h2><label class="form-label" for="pass_score">Batas lulus (0–100)</label><input name="pass_score" id="pass_score" type="number" min="0" max="100" step="0.0001" class="form-control mb-3" value="{{ old('pass_score') }}"><label class="form-label" for="rounding">Pembulatan sebelum huruf/kelulusan</label><select id="rounding" name="rounding" class="form-select mb-3"><option value="">Belum ditentukan</option><option value="half_up">Terdekat, setengah ke atas</option><option value="floor">Ke bawah</option><option value="ceil">Ke atas</option></select><label class="form-label" for="precision">Jumlah desimal (0–4)</label><input id="precision" name="precision" class="form-control mb-3" type="number" min="0" max="4" value="{{ old('precision') }}"><label class="form-label" for="bands">Nilai huruf: satu baris label:batas bawah; wajib mencakup 0</label><textarea id="bands" name="bands" class="form-control mb-3" rows="5">{{ old('bands') }}</textarea><label class="form-label" for="late_policy">Keterlambatan</label><select id="late_policy" name="late_policy" class="form-select mb-3"><option value="">Belum ditentukan</option><option value="review">Wajib keputusan penerimaan terlambat per laporan</option><option value="no_penalty">Diterima tanpa penalti otomatis sesuai ketentuan</option></select><label class="d-block mb-3"><input type="checkbox" name="separate_activity5" value="1"> Ketentuan resmi menetapkan nilai Aktivitas 5 dan laporan akhir sebagai komponen terpisah.</label><label class="form-label" for="authority_note">Dasar aturan / bagian yang masih menunggu ketentuan</label><textarea id="authority_note" name="authority_note" class="form-control mb-3" required minlength="5">{{ old('authority_note') }}</textarea><button type="submit" class="btn btn-primary">Simpan draf aturan</button></div></form>
@forelse($rules as $rule)@php $cfg=json_decode($rule->config_json,true); $issues=$service->validateRules($o->id,$cfg); @endphp<div class="card mb-3"><div class="card-body"><h2>Versi {{ $rule->version }} · {{ $rule->status==='draft'?'Draf — belum resmi':'Diterbitkan' }}</h2><p>{{ $cfg['authority_note'] }}</p><p>Batas lulus {{ $cfg['pass_score']??'belum ditentukan' }} · Pembulatan {{ $cfg['rounding']??'belum ditentukan' }} / {{ $cfg['precision']??'—' }} desimal · Keterlambatan {{ $cfg['late_policy']??'belum ditentukan' }}</p><ul>@foreach($cfg['components'] as $c)<li>{{ $c['label'] }}: {{ $c['weight']??'Belum ditentukan' }}% / maksimum {{ $c['max_score'] }} · {{ $c['active']?'Aktif':'Nonaktif' }}</li>@endforeach</ul><p>Huruf: @foreach($cfg['bands'] as $band){{ $band['letter'] }} ≥ {{ $band['minimum'] }}; @endforeach</p>@if($issues)<ul class="text-danger">@foreach($issues as $issue)<li>{{ $issue }}</li>@endforeach</ul>@endif
@if($rule->status==='draft')<form method="post" action="{{ route('grades.rules.publish',[$o->id,$rule->id]) }}" data-dirty-form data-confirm="Terbitkan versi aturan ini sebagai dasar finalisasi?">@csrf<label class="form-label">Alasan penerbitan<input name="reason" class="form-control mb-2" required minlength="5"></label><label class="d-block mb-3"><input name="confirmed" type="checkbox" value="1" required> Saya memastikan aturan sesuai ketentuan resmi.</label><button class="btn btn-primary" type="submit" @disabled(count($issues)>0)>Terbitkan versi {{ $rule->version }}</button></form>@endif</div></div>@empty<p>Belum ada versi aturan.</p>@endforelse
{{ $rules->links() }}
@endsection
