@extends('layouts.app')
@section('context',$o->semester.' · '.$o->name)
@section('content')
<x-page-header :title="$a->title" :subtitle="$e->nbi.' · '.$e->name.' · '.$e->session_label" :crumbs="$a->type === 'final' ? ['Laporan akhir' => route('final-reports.index', $o->id), $e->name => null] : ['Pengumpulan' => route('collections.index', $o->id), 'Penerimaan' => route('submissions.index', [$o->id, $a->id]), $e->name => null]" />
@if(!$schedule)<div class="alert alert-warning">Jadwal pengumpulan belum tersedia untuk sesi ini. <a href="{{ route('assignments.schedules',[$o->id,$a->id]) }}">Atur jadwal</a></div>@else
<p class="small text-secondary">Deadline {{ \Carbon\CarbonImmutable::parse($schedule->due_at,'UTC')->setTimezone('Asia/Jakarta')->format('d/m/Y H:i') }} WIB · {{ $schedule->allow_late?'Terlambat diizinkan hingga penutupan':'Terlambat tidak diizinkan' }}. Waktu input dan penerima dicatat otomatis saat menyimpan.</p>
@if($finalized)<div class="alert alert-info">Hasil final sudah diarsipkan; penerimaan read-only.</div>@endif
<form method="post" enctype="multipart/form-data" action="{{ route('submissions.save',[$o->id,$a->id,$e->id]) }}" class="card mb-3" data-dirty-form>@csrf<div class="card-body"><fieldset @disabled($finalized)><input type="hidden" name="version" value="{{ old('version',$sub?->version??0) }}"><label for="status" class="form-label">Status penerimaan</label><select id="status" name="status" class="form-select mb-3">@foreach($states as $key=>$label)<option value="{{ $key }}" @selected(old('status',$sub?->status)===$key)>{{ $label }}</option>@endforeach</select><label for="received_at" class="form-label">Waktu terima sebenarnya · WIB</label><input id="received_at" name="received_at" type="datetime-local" class="form-control mb-3" value="{{ old('received_at',$sub?->received_at?\Carbon\CarbonImmutable::parse($sub->received_at,'UTC')->setTimezone('Asia/Jakarta')->format('Y-m-d\TH:i'):'') }}"><p class="small text-secondary">Kosongkan jika diputuskan tidak dikumpulkan. Keterlambatan dihitung dari waktu terima ini, bukan waktu input.</p>
@if($a->mode==='digital')<label for="file" class="form-label">File digital / versi revisi</label><input type="file" id="file" name="file" class="form-control mb-3" accept=".pdf,.docx,.zip,.txt,.sql"><p class="small text-secondary">Maksimum {{ config('academic.upload_max_kb')/1024 }} MB. File revisi hanya setelah Perlu revisi, di dalam periode penerimaan. File lama tetap privat dan tersedia.</p>@endif
<label for="late_decision" class="form-label">Keputusan keterlambatan</label><select id="late_decision" name="late_decision" class="form-select mb-3"><option value="pending" @selected(old('late_decision',$sub?->late_decision)==='pending')>Menunggu / tidak relevan</option><option value="accepted" @selected(old('late_decision',$sub?->late_decision)==='accepted')>Diterima dengan alasan</option></select><label for="note" class="form-label">Catatan internal</label><textarea id="note" name="note" class="form-control mb-3">{{ old('note',$sub?->note) }}</textarea><label for="student_note" class="form-label">Catatan untuk praktikan (opsional)</label><textarea id="student_note" name="student_note" class="form-control" maxlength="1000">{{ old('student_note',$sub?->student_note) }}</textarea><div class="form-text">Terlihat oleh praktikan di Cek Status. Jangan tulis nama, NBI, atau nilai.</div><div class="mb-3"></div><label for="reason" class="form-label">Alasan — wajib bila mengoreksi penerimaan yang sudah tersimpan</label><textarea id="reason" name="reason" class="form-control mb-3">{{ old('reason') }}</textarea><button class="btn btn-primary" type="submit">Simpan penerimaan</button></fieldset></div></form>
@endif
@if($items->isNotEmpty() && $sub)<form method="post" action="{{ route('submissions.checklist',[$o->id,$a->id,$e->id]) }}" class="card mb-3" data-dirty-form>@csrf<div class="card-body"><h2>Checklist laporan · {{ $e->name }}</h2><fieldset @disabled($finalized || in_array($sub->status,['complete','missing_decided']))><input type="hidden" name="version" value="{{ $sub->version }}">@foreach($items as $item)<label class="d-block mb-2"><input type="checkbox" name="completed[]" value="{{ $item->id }}" @checked(in_array($item->id,$checked))> {{ $item->label }}</label>@endforeach<label class="form-label mt-3" for="check-reason">Alasan — wajib bila mengoreksi checklist tersimpan</label><input id="check-reason" name="reason" class="form-control mb-3" maxlength="1000"><button type="submit" class="btn btn-primary">Simpan checklist</button></fieldset><p class="small text-secondary mt-2">Checklist tidak menambah nilai. Untuk koreksi laporan Selesai, ubah status menjadi Perlu revisi terlebih dahulu.</p></div></form>@endif
@if($sub)<details class="card mb-3"><summary class="card-body">Riwayat penerimaan dan revisi ({{ count($history) }})</summary><div class="card-body"><ol>@foreach($history as $event)@php $value=json_decode($event->after_json,true); @endphp<li class="mb-2">{{ $states[$value['status']]??$value['status'] }} · Terima {{ !empty($value['received_at'])?\Carbon\CarbonImmutable::parse($value['received_at'],'UTC')->setTimezone('Asia/Jakarta')->format('d/m/Y H:i'):'—' }} WIB · Input {{ \Carbon\CarbonImmutable::parse($event->created_at,'UTC')->setTimezone('Asia/Jakarta')->format('d/m/Y H:i') }} WIB · Pengelola {{ DB::table('users')->where('id',$event->actor_id)->value('name') }} @if($event->reason)<br>{{ $event->reason }}@endif</li>@endforeach</ol></div></details>@endif
@if($a->mode==='digital')<div class="card"><div class="card-body"><h2>Riwayat versi privat</h2><ul>@forelse($versions as $v)<li>Versi {{ $v->version_number }} · <a href="{{ route('submissions.download',[$o->id,$a->id,$e->id,$v->id]) }}">{{ $v->original_name }}</a> · {{ \Carbon\CarbonImmutable::parse($v->submitted_at,'UTC')->setTimezone('Asia/Jakarta')->format('d/m/Y H:i') }} WIB</li>@empty<li>Belum ada file.</li>@endforelse</ul></div></div>@endif
@endsection
